# Generated by Django 6.0.1 on 2026-01-28 07:40

import user.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', user.manager.UserManager()),
            ],
        ),
    ]
